export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const LOAD_COURSES_SUCESS = 'LOAD_COURSES_SUCESS';
export const LOAD_AUTHORS_SUCESS = 'LOAD_AUTHORS_SUCESS';
